---

- name: DebOps pre_tasks hook
  include: "{{ lookup('task_src', 'users/pre_main.yml') }}"

- include: enforce_root.yml
  when: users

- include: users.yml
  when: users

- include: forward.yml
  when: users

- include: sshkeys.yml
  when: users

- include: ssh_configs.yml
  when: users

- include: dotfiles.yml
  when: users
  tags: users-dotfiles

- name: DebOps post_tasks hook
  include: "{{ lookup('task_src', 'users/post_main.yml') }}"

